config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks"}, :skip => [:registrations]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#index'
  
  resources :users, only: [:show] do
    resources :profile, only: [:edit, :update]
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/authorization.rb
class Authorization < ApplicationRecord
  belongs_to :user

  after_create :fetch_details

  def fetch_details
    self.send("fetch_details_from_#{self.provider.downcase}")
  end
  #
  # def fetch_details_from_facebook
  #   graph = Koala::Facebook::API.new(self.token)
  #   facebook_data = graph.get_object("me")
  #   self.save
  # end
  #
  # def fetch_details_from_twitter
  # end


  def fetch_details_from_github
  end

  def fetch_details_from_google_oauth2
  end
  
end

app/models/issue.rb
class Issue < ApplicationRecord
  belongs_to :repository
  belongs_to :user
end

app/models/language.rb
class Language < ApplicationRecord
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
end

app/models/repository.rb
class Repository < ApplicationRecord
  belongs_to :user
end

app/models/repository_language.rb
class RepositoryLanguage < ApplicationRecord
  belongs_to :language
  belongs_to :repository
end

app/models/tfile.rb
class Tfile < ApplicationRecord
  belongs_to :repository
end

app/models/translation.rb
class Translation < ApplicationRecord
  belongs_to :tfile
  belongs_to :language
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :recoverable, :rememberable, :trackable, :validatable, :omniauthable, :omniauth_providers => [:github]

  has_many :authorizations, dependent: :destroy
  has_one :profile, dependent: :destroy

  # Create session
 def self.new_with_session(params,session)
   if session["devise.user_attributes"]
     new(session["devise.user_attributes"],without_protection: true) do |user|
       user.attributes = params
       user.valid?
     end
   else
     super
   end
 end

 # Omniauth authorize or create user
 # TODO: Profile picture and username should
 def self.from_omniauth(auth, current_user)
   authorization = Authorization.where(:provider => auth.provider, :uid => auth.uid.to_s, :token => auth.credentials.token, :secret => auth.credentials.secret).first_or_initialize
   @a = auth
   if authorization.user.blank?
     user = current_user || User.where('email = ?', auth["info"]["email"]).first
     if user.blank?
       user = User.new
       user.email = auth.info.email
       user.password = Devise.friendly_token[0,10]
       user.profile = Profile.new(name: auth.info.name, picture: auth.info.image, username:auth.info.nickname, bio: auth.extra.raw_info.bio, website: auth.extra.raw_info.blog)
       user.save
     end
     authorization.user_id = user.id
     authorization.save
   end
   authorization.user
 end

  private

  def password_required?
    self.authorizations.size < 1 && super
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController

	def all
		user = User.from_omniauth(request.env["omniauth.auth"], current_user)
		if user.persisted?
			flash[:notice] = "Giriş işlemi başarılı."
			sign_in_and_redirect(user, :event => :authentication)
		else
			session["devise.user_attributes"] = user.attributes
			redirect_to new_user_registration_url
		end
	end

	def failure
	  #TODO: Başarısız mantığını yaz ve super'i ekle.
		super
	end


	# alias_method :facebook, :all
	# alias_method :twitter, :all
	# alias_method :linkedin, :all
	alias_method :github, :all
	alias_method :passthru, :all
	# alias_method :google_oauth2, :all
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @User = User.includes(:profile).find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/_guest.slim
div class="panel-group"
  div class="panel panel-default"
    div class="panel-heading"
       | Çeviri Yönetim Sistemine Giriş Yap

    div class="panel-body"
        p
        | Çeviri Yönetim Sistemine Hoşgeldiniz
        p
        | README ler, AWESOME ler ve diğer Markdown tipi dokümanları 
        | kolaylıkla çevirmenizi sağlayan bu araç sayesinde birden çok 
        | içerik üzerinde eş zamanlı olarak ekip halinde çevirilerinizi 
        | yürütebilirsiniz!
        p
        | Sistem GitHub'a tam entegre olarak kuruludur. Tüm işlemlerinizi 
        | GitHub üyeliğiniz saysinde istediğiniz cihazdan kolaylıkla 
        | gerçekleştirebilirsiniz!
        div class="btn-group btn-group-justified"
          =link_to 'GitHub ile Giriş Yap', new_user_session_path, class: 'btn btn-success'

app/views/home/_member.slim
=link_to 'Çıkış', destroy_user_session_path, :method => :delete
hr
=link_to 'Profile', user_path(current_user)
=current_user.profile.inspect
br
=image_tag(current_user.profile.picture) if current_user.profile.picture

app/views/home/index.slim
-unless user_signed_in?
  =render 'guest'
-else
  =render 'member'

app/views/layouts/application.slim
doctype html
html
  head
    title
      | CeviriYonetim
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  body
    = render 'shared/alerts'
    
    = render 'shared/header'
    
    = render 'shared/menu'
    
    .container
      = yield
    
    = render 'shared/footer'

app/views/shared/_alerts.slim
- if notice
  p.notice
    = notice
- if alert
  p.alert
    = alert

app/views/shared/_header.slim
div class="header"
  center
    h1 Çeviri Yönetim Sistemi

app/views/shared/_menu.slim
nav.navbar.navbar-default.navbar-fixed-top
  .container
    .navbar-header
      button.navbar-toggle.collapsed aria-controls="navbar" aria-expanded="false" data-target="#navbar" data-toggle="collapse" type="button" 
        span.sr-only Toggle navigation
        span.icon-bar
        span.icon-bar
        span.icon-bar
      =link_to 'Çeviri Yönetim', root_path, class:"navbar-brand"
    #navbar.navbar-collapse.collapse
      ul.nav.navbar-nav
        =active_link_to 'Anasayfa', root_path, wrap_tag: :li, active: :exact

      ul.nav.navbar-nav.navbar-right
        -if user_signed_in?
          =active_link_to 'Profil', user_path(current_user), wrap_tag: :li
          =active_link_to 'Çıkış', destroy_user_session_path, method: :delete, wrap_tag: :li
        -else
          =active_link_to 'Giriş', new_user_session_path, wrap_tag: :li
          

    /! /.nav-collapse

app/views/users/show.slim
-if current_user.id == @User.id
  =link_to 'Düzenle', edit_user_profile_path(current_user), class:"btn btn-warning"
=@User.inspect
=@User.profile.inspect